### ISSUE TITLE
ruby/2.6.0/open3.rb:213:in `spawn': Permission denied (Errno::EACCES)

### ISSUE THREAD

**Issue by Jigyasa3** [takaram/kofam_scan#2]
Hey @takaram 

I am running the kofam_scan software giving the paths to parallel, hmmsearch to config.yml file. But I am getting the following error-

#my config.yml file-
profile: /work/student/jigyasa-arora/kofamscan/db/profiles

# Path to the KO list file
ko_list: /work/student/jigyasa-arora/kofamscan/db/ko_list

# Path to an executable file of hmmsearch
# You do not have to set this if it is in your $PATH
hmmsearch: /apps/free72/hmmer/3.1b2/bin 

# Path to an executable file of GNU parallel
# You do not have to set this if it is in your $PATH
parallel: /home/j/jigyasa-arora/local/parallel-20191022/src

#the code I am running-
$/work/student/jigyasa-arora/kofamscan/bin/kofamscan-1.1.0/exec_annotation -o 230-01-kopfam 230-01-prokka.faa

#error-
Traceback (most recent call last):
        8: from /work/student/jigyasa-arora/kofamscan/bin/kofamscan-1.1.0/exec_annotation:7:in `<main>'
        7: from /work/student/jigyasa-arora/kofamscan/bin/kofamscan-1.1.0/lib/kofam_scan/cli.rb:21:in `run'
        6: from /work/student/jigyasa-arora/kofamscan/bin/kofamscan-1.1.0/lib/kofam_scan/executor.rb:8:in `execute'
        5: from /work/student/jigyasa-arora/kofamscan/bin/kofamscan-1.1.0/lib/kofam_scan/executor.rb:35:in `execute'
        4: from /work/student/jigyasa-arora/kofamscan/bin/kofamscan-1.1.0/lib/kofam_scan/executor.rb:74:in `run_hmmsearch'
        3: from /work/student/jigyasa-arora/kofamscan/bin/kofamscan-1.1.0/lib/kofam_scan/parallel.rb:27:in `exec'
        2: from /home/j/jigyasa-arora/lib/ruby/2.6.0/open3.rb:101:in `popen3'
        1: from /home/j/jigyasa-arora/lib/ruby/2.6.0/open3.rb:213:in `popen_run'
/home/j/jigyasa-arora/lib/ruby/2.6.0/open3.rb:213:in `spawn': Permission denied - /home/j/jigyasa-arora/local/parallel-20191022 (Errno::EACCES)

**Comment by takaram** [comment]
You have to give the path of the command file instead of directory in which the command is located.
In your case, `hmmsearch: /apps/free72/hmmer/3.1b2/bin/hmmsearch` and `parallel: /home/j/jigyasa-arora/local/parallel-20191022/src/parallel` are the correct setting.

**Comment by Jigyasa3** [comment]
Thank you it's working now!
