### ISSUE TITLE
How to deal hmm files without a threshold & F-measure info

### ISSUE THREAD

**Issue by jlli6t** [takaram/kofam_scan#6]
Hi, 

How does kofam_scan deal with hmm file that without "threshold       score_type      profile_type    F-measure" these 4 columns information in file "ko_list", it seems to me that there will never be a valid hit of those hmms.

Thank you,
Jie

**Comment by jlli6t** [comment]
And seems due to the situation like this, sequences are hitting other hmms positively and return those (lack important info) as negative hit.

**Comment by takaram** [comment]
As you noticed, you will not see KOs without thresolds as a "valid" hit. It is a weak point of this tool :(

**Comment by jlli6t** [comment]
Ye I see, thanks anyway
