### ISSUE TITLE
bin/lib/kofam_scan/parallel.rb:28:in `write': Broken pipe (Errno::EPIPE)

### ISSUE THREAD

**Issue by PandengWang** [takaram/kofam_scan#7]
Thanks for providing so useful tool!
When I used it, I encountered a error as follows:

> /mdata/xxx/software/miniconda3/bin/lib/kofam_scan/parallel.rb:28:in `write': Broken pipe (Errno::EPIPE)
>         from /mdata/xxx/software/miniconda3/bin/lib/kofam_scan/parallel.rb:28:in `puts'
>         from /mdata/xxx/software/miniconda3/bin/lib/kofam_scan/parallel.rb:28:in `block in exec'
>         from /mdata/xxx/software/miniconda3/lib/ruby/2.5.0/open3.rb:205:in `popen_run'
>         from /mdata/xxx/software/miniconda3/lib/ruby/2.5.0/open3.rb:95:in `popen3'
>         from /mdata/xxx/software/miniconda3/bin/lib/kofam_scan/parallel.rb:27:in `exec'
>         from /mdata/xxx/software/miniconda3/bin/lib/kofam_scan/executor.rb:107:in `run_hmmsearch'
>         from /mdata/xxx/software/miniconda3/bin/lib/kofam_scan/executor.rb:35:in `execute'
>         from /mdata/xxx/software/miniconda3/bin/lib/kofam_scan/executor.rb:8:in `execute'
>         from /mdata/xxx/software/miniconda3/bin/lib/kofam_scan/cli.rb:21:in `run'
>         from /mdata/xxx/software/miniconda3/bin/exec_annotation:7:in `<main>'
> 

Do you have any idea about how to solve this problem?
Thanks so much!

Pandeng

**Comment by takaram** [comment]
Hmm... sorry I have no idea about the error. Do you get it every time? Do you run more than one KofamScan in parallel?

**Comment by PandengWang** [comment]
> Hmm... sorry I have no idea about the error. Do you get it every time? Do you run more than one KofamScan in parallel?

Yes, I encountered this error every time when I annotated my whole protein seqs (16762174). 
But, when I used a subset of the protein seqs, such as 200, it didn't report this error.

The comment I run: `exec_annotation -o y19-all15_prot_kegg.annotations ../4.genePrediction/y19-all15_prot_catalogue_relabel.faa -p /software/xxx/kegg/kofam/profiles/ -k /software/xxx/kegg/kofam/ko_list --cpu=1 --tmp-dir=/mdata/xxx/tmp -f mapper-one-line --no-report-unannotated`

**Comment by achmall** [comment]
I get the same error when trying to run kofamscan on a server, whereas it is working fine with the same input file on my local machine... 
`$ ./exec_annotation -o 26052020_kofamscan_HACON.txt /export/work_cgb/Achim/HACON_sequencing/200408_K00253.A.Project_Mall-DNA1-2020-02-13/gene_calls_aa.fa
Traceback (most recent call last):
	10: from ./exec_annotation:7:in `<main>'
	 9: from /export/work_cgb/Achim/kofam_scan/lib/kofam_scan/cli.rb:21:in `run'
	 8: from /export/work_cgb/Achim/kofam_scan/lib/kofam_scan/executor.rb:8:in `execute'
	 7: from /export/work_cgb/Achim/kofam_scan/lib/kofam_scan/executor.rb:35:in `execute'
	 6: from /export/work_cgb/Achim/kofam_scan/lib/kofam_scan/executor.rb:107:in `run_hmmsearch'
	 5: from /export/work_cgb/Achim/kofam_scan/lib/kofam_scan/parallel.rb:27:in `exec'
	 4: from /export/home/sey013/.conda/envs/kofamscan/lib/ruby/2.6.0/open3.rb:101:in `popen3'
	 3: from /export/home/sey013/.conda/envs/kofamscan/lib/ruby/2.6.0/open3.rb:219:in `popen_run'
	 2: from /export/work_cgb/Achim/kofam_scan/lib/kofam_scan/parallel.rb:28:in `block in exec'
	 1: from /export/work_cgb/Achim/kofam_scan/lib/kofam_scan/parallel.rb:28:in `puts'
/export/work_cgb/Achim/kofam_scan/lib/kofam_scan/parallel.rb:28:in `write': Broken pipe (Errno::EPIPE)
`

**Comment by li0604** [comment]
![image](https://user-images.githubusercontent.com/54136123/128601965-29d7ea62-4d14-48d6-9932-82f15ade09dc.png)

The same problem. Does anybody know how to solve it?

**Comment by PandengWang** [comment]
Hi All,

I may have figured out the reason underlying this error.
This error come from Linux `parallel` command, which is called in `exec_annotation`.
When you close your shell window, the Linux `parallel` will recieve signal and won't submit new jobs, even you run `parallel` with `nohup`. 
One possible method to resolve this issue is that after you run `exec_annotation` with `nohup` in the backgroud, you could disconnect this command with your current shell using `disown -h %jobid` or `disown -a`.

Hope this message will help you guy who have encountered the same error.

Pandeng

**Comment by imonteroo** [comment]
Running:
`exec_annotation "$output_dir/${sample}_proteins.faa"   -o "$output_dir/kofamscan_output/*.proteins.faa;"   --cpu 6   -f mapper`
I have this error:
```
/media/microviable/d/miniconda3/envs/kofamscan/lib/ruby/3.4.0/open3.rb:534:in 'Kernel#spawn': No such file or directory - /usr/local/bin/parallel (Errno::ENOENT)
	from /media/microviable/d/miniconda3/envs/kofamscan/lib/ruby/3.4.0/open3.rb:534:in 'Open3.popen_run'
	from /media/microviable/d/miniconda3/envs/kofamscan/lib/ruby/3.4.0/open3.rb:235:in 'Open3.popen3'
	from /media/microviable/d/miniconda3/envs/kofamscan/bin/lib/kofam_scan/parallel.rb:27:in 'KofamScan::Parallel#exec'
	from /media/microviable/d/miniconda3/envs/kofamscan/bin/lib/kofam_scan/executor.rb:107:in 'KofamScan::Executor#run_hmmsearch'
	from /media/microviable/d/miniconda3/envs/kofamscan/bin/lib/kofam_scan/executor.rb:35:in 'KofamScan::Executor#execute'
	from /media/microviable/d/miniconda3/envs/kofamscan/bin/lib/kofam_scan/executor.rb:8:in 'KofamScan::Executor.execute'
	from /media/microviable/d/miniconda3/envs/kofamscan/bin/lib/kofam_scan/cli.rb:21:in 'KofamScan::CLI.run'
	from /media/microviable/d/miniconda3/envs/kofamscan/bin/exec_annotation:7:in '<main>'
```
```
ruby --version
ruby 3.4.2 (2025-02-15 revision d2930f8e7a) +PRISM [x86_64-linux]
```
```
parallel --version
GNU parallel 20250222
Copyright (C) 2007-2025 Ole Tange, http://ole.tange.dk and Free Software
Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
GNU parallel comes with no warranty.

Web site: https://www.gnu.org/software/parallel

When using programs that use GNU Parallel to process data for publication
please cite as described in 'parallel --citation'.
```
