### ISSUE TITLE
Error: Unknown KO:

### ISSUE THREAD

**Issue by timregan** [takaram/kofam_scan#8]
Hi,
I've seen a few Errors recently and wondered if you knew what might be causing them, or better still, how to fix them!
Error message examples:
kofamscan/bin/lib/kofam_scan/executor.rb:54:in `delete': No such file or directory @ apply2files - ./tmp/tabular/K20351 (Errno::ENOENT)
...
kofamscan/bin/lib/kofam_scan/executor.rb:62:in `initialize': No such file or directory @ rb_sysopen - ./tmp/tabular/K06344 (Errno::ENOENT)

Otherwise, it outputs a file just fine with plenty of hits, but I'm seeing more than a few of these.

Best wishes and thanks,
Tim

**Comment by takaram** [comment]
Maybe you ran more than one KoScan in parallel, and used same tmpdir.
If so, you should use `--tmp-dir` option with different directory for every process. Otherwise intermediate files for different queries are mixed, causing an error or a wrong result.

**Comment by timregan** [comment]
That was exactly the problem! Thanks so much. :)
