### ISSUE TITLE
How to compare multi hmm hits from one protein sequence

### ISSUE THREAD

**Issue by jlli6t** [takaram/kofam_scan#9]
Hi takaram,

Once hit score is over the threshold, then this hit will be marked as valid hit, resulted in some multi hits for one sequence.
But, each hmm has its own threhold, which makes me a little bit confusing, as seems like these thresholds are not comparable to each other.

How would you suggest us to deal with multi hmm hits from one protein sequence?

**Comment by takaram** [comment]
There may be many ways to interpret such hits.
For example, you can use "F-measure" in `ko_list`, because it reflects the reliability of the HMM (reliable when F-measure close to 1).
